Repository radix-ui/primitives, pull requests merged in 2020-12, with the labels that each got.

#352 Correct readme links
  README.md
Labels: documentation

#354 Tests: AccessibleIcon
  packages/react/accessible-icon/src/AccesibleIcon.test.tsx
Labels: testing

#356 Tests: Dialog
  packages/react/dialog/src/Dialog.test.tsx
Labels: testing

#357 Test: AlertDialog
  packages/react/alert-dialog/src/AlertDialog.test.tsx
Labels: testing

#355 Tests: Accordion
  packages/react/accordion/src/Accordion.test.tsx
Labels: testing

#353 Speed up pre-commit hooks with lint-staged
  .gitignore
  .yarn/versions/e9905fee.yml
  package.json
  yarn.lock
Labels: enhancement
