Repository radix-ui/primitives, pull requests merged in 2021-01, with the labels that each got.

#362 Test: Arrow
  packages/react/arrow/src/Arrow.test.tsx
Labels: testing

#363 Test: AspectRatio
  packages/react/aspect-ratio/src/AspectRatio.test.tsx
Labels: testing

#366 Test: Checkbox
  packages/react/checkbox/src/Checkbox.test.tsx
Labels: testing

#364 Test: Avatar
  packages/react/avatar/src/Avatar.test.tsx
Labels: testing

#359 [Popper] Add window size explicit dependency
  .yarn/versions/a6bd4f3f.yml
  packages/core/popper/src/popper.stories.tsx
  packages/core/popper/src/popper.ts
  packages/core/utils/src/geometry.ts
  packages/react/popper/src/Popper.tsx
Labels: bug

#378 [react-utils]: Fix return value from useCallbackRef
  .yarn/versions/f61bc288.yml
  packages/react/utils/src/useCallbackRef.tsx
Labels: bug

#379 ScrollArea: Temporary workaround for double render (#351)
  .yarn/versions/257b7174.yml
  packages/react/scroll-area/src/ScrollArea.stories.tsx
  packages/react/scroll-area/src/ScrollArea.tsx
Labels: enhancement

#382 Test: FocusScope
  .yarn/versions/bf99b01a.yml
  package.json
  packages/react/focus-scope/src/FocusScope.test.tsx
  yarn.lock
Labels: testing

#392 Remove unnecessary package resolutions
  package.json
Labels: housekeeping

#361 Build with Parcel monorepo script
  .yarn/versions/970578a9.yml
  package.json
  packages/core/popper/package.json
  packages/core/utils/package.json
  packages/react/accessible-icon/package.json
  packages/react/accordion/package.json
  packages/react/alert-dialog/package.json
  packages/react/announce/package.json
  packages/react/arrow/package.json
  packages/react/aspect-ratio/package.json
  packages/react/avatar/package.json
  packages/react/checkbox/package.json
  packages/react/collapsible/package.json
  packages/react/collection/package.json
  packages/react/context-menu/package.json
  packages/react/dialog/package.json
  packages/react/dismissable-layer/package.json
  packages/react/dropdown-menu/package.json
  packages/react/focus-guards/package.json
  packages/react/focus-scope/package.json
  packages/react/label/package.json
  packages/react/menu/package.json
  packages/react/polymorphic/package.json
  packages/react/popover/package.json
  packages/react/popper/package.json
  packages/react/portal/package.json
  packages/react/presence/package.json
  packages/react/progress/package.json
  packages/react/radio-group/package.json
  packages/react/roving-focus/package.json
  packages/react/scroll-area/package.json
  packages/react/separator/package.json
  packages/react/slider/package.json
  packages/react/switch/package.json
  packages/react/tabs/package.json
  packages/react/toggle-button/package.json
  packages/react/tooltip/package.json
  packages/react/utils/package.json
  packages/react/visually-hidden/package.json
  yarn.lock
Labels: debt

#395 [FocusScope] Fix vanishing blur issue
  .yarn/versions/23cdd195.yml
  packages/react/focus-scope/src/FocusScope.test.tsx
  packages/react/focus-scope/src/createFocusScope.tsx
  packages/react/menu/src/Menu.tsx
  packages/react/popover/src/Popover.tsx
Labels: bug

#394 [Popover][DropdownMenu] Fix race condition when dismissing via click outside and `disableOutsidePointerEvents` is off.
  .yarn/versions/f17394b2.yml
  packages/react/dropdown-menu/src/DropdownMenu.tsx
  packages/react/menu/src/Menu.tsx
  packages/react/popover/src/Popover.stories.tsx
  packages/react/popover/src/Popover.tsx
Labels: bug
